USE [master]
GO
/****** Object:  Database [AngularDemoclass]    Script Date: 20-09-2020 12:49:05 ******/
CREATE DATABASE [AngularDemoclass]
GO
ALTER DATABASE [AngularDemoclass] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AngularDemoclass].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AngularDemoclass] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AngularDemoclass] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AngularDemoclass] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AngularDemoclass] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AngularDemoclass] SET ARITHABORT OFF 
GO
ALTER DATABASE [AngularDemoclass] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AngularDemoclass] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AngularDemoclass] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AngularDemoclass] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AngularDemoclass] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AngularDemoclass] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AngularDemoclass] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AngularDemoclass] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AngularDemoclass] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AngularDemoclass] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AngularDemoclass] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AngularDemoclass] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AngularDemoclass] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AngularDemoclass] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AngularDemoclass] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AngularDemoclass] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AngularDemoclass] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AngularDemoclass] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [AngularDemoclass] SET  MULTI_USER 
GO
ALTER DATABASE [AngularDemoclass] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AngularDemoclass] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AngularDemoclass] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AngularDemoclass] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AngularDemoclass] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AngularDemoclass] SET QUERY_STORE = OFF
GO
USE [AngularDemoclass]
GO
/****** Object:  Table [dbo].[Employee]    Script Date: 20-09-2020 12:49:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employee](
	[PKEmployeeId] [int] IDENTITY(1,1) NOT NULL,
	[EmployeeName] [varchar](100) NOT NULL,
	[EmployeeSalary] [decimal](18, 2) NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED 
(
	[PKEmployeeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Employee] ON 
GO
INSERT [dbo].[Employee] ([PKEmployeeId], [EmployeeName], [EmployeeSalary], [IsActive]) VALUES (1, N'Scott', CAST(25000.00 AS Decimal(18, 2)), 1)
GO
INSERT [dbo].[Employee] ([PKEmployeeId], [EmployeeName], [EmployeeSalary], [IsActive]) VALUES (2, N'Sam', CAST(35000.00 AS Decimal(18, 2)), 1)
GO
SET IDENTITY_INSERT [dbo].[Employee] OFF
GO
USE [master]
GO
ALTER DATABASE [AngularDemoclass] SET  READ_WRITE 
GO

